version: '3.3'
services:
    db:
        image: mysql
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password

        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : <MySQL Port running inside container>
            - '3306:3306'
        expose:
            # Opens port 3306 on the container
            - '3306'
            # Where our data will be persisted
        volumes:
            - my-db:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d

# Names our volume
volumes:
    my-db:
