version: '3.3'
services:
    db:
        image: mysql:8.0-oraclelinux8
        restart: always
        command: mysqld --default-authentication-plugin=mysql_native_password

        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'

        volumes:
            - my-db:/var/lib/mysql
            - ./dump:/docker-entrypoint-initdb.d

volumes:
    my-db:
