


export const env = {
    SUPA_CONNECT_CLIENT_ID: process.env.SUPA_CONNECT_CLIENT_ID,
    SUPA_CONNECT_CLIENT_SECRET: process.env.SUPA_CONNECT_CLIENT_SECRET,
    NEXT_PUBLIC_URL: process.env.NEXT_PUBLIC_URL,
}